package com.antcashmanager.android.analytics

/**
 * Shared constants for analytics tracking.
 */
object AnalyticsConstants {
    const val TAG = "AnalyticsManager"
    const val MAX_NAME_LENGTH = 40
    const val SCREEN_CLASS_COMPOSE_NAV_HOST = "ComposeNavHost"

    val ALLOWED_USAGE_EVENTS = setOf(
        "transactions_filter_applied",
        "transactions_filter_cleared",
        "transaction_add_opened",
        "receipt_scan_opened",
        "transaction_form_opened",
        "transaction_form_cancelled",
        "transaction_submit_success",
        "transaction_deleted",
        "transaction_shared",
        "backup_create_requested",
        "backup_file_saved",
        "backup_file_save_error",
        "restore_open_requested",
        "restore_file_selected",
        "delete_all_data_confirmed",
        "reset_preferences_confirmed",
        "delete_suggestions_confirmed",
        "category_created",
        "category_deleted",
        "categories_reordered",
        "categories_reorder_opened",
        "category_hidden",
        "category_shown",
        "chart_date_filter_changed",
        "chart_custom_date_range_set",
        "chart_shared",
        "chart_help_opened",
        "home_top_cards_reordered",
        "home_date_filter_changed",
        "home_search_opened",
        "home_help_opened",
        "receipt_scan_captured",
        "receipt_scan_saved",
        "receipt_scan_amount_edited",
        "data_encryption_toggled",
        "suggestions_toggled",
        "home_quick_insights_toggled",
        "date_format_changed",
        "transaction_display_type_changed",
        "theme_changed",
        "language_changed",
        "currency_format_changed",
        "feedback_email_sent",
        "tutorial_replay_requested",
        "decimal_digits_changed",
        "decimal_separator_changed",
        "thousands_separator_changed",
        "meal_voucher_value_changed",
        "mask_amounts_toggled",
        "show_charts_section_toggled",
        "charts_zoom_toggled",
        "show_payment_breakdown_toggled",
        "show_transaction_notes_toggled",
        "widget_background_color_changed",
        "widget_opacity_changed",
        "widget_recent_transactions_opened",
        "widget_category_breakdown_opened",
        "settings_help_opened",
        "settings_privacy_policy_opened",
        "settings_third_party_libraries_opened",
        "settings_high_contrast_toggled",
        "settings_large_text_toggled",
        "settings_reduce_motion_toggled",
        "transactions_filter_opened",
        "transactions_help_opened",
        "categories_help_opened",
        "receipt_scan_retry",
        "transaction_recurring_toggled",
        "home_transaction_detail_opened",
        "home_search_submitted",
        "home_search_cleared",
        "transaction_form_validation_failed",
        "receipt_scan_failed",
        "receipt_scan_manual_entry",
        "empty_state_action_taken",
        "chart_loading_completed",
        "settings_dialog_dismissed",
    )
}

